# Generated by Django 6.0.1 on 2026-02-01 19:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('license_number', models.CharField(max_length=50, verbose_name='Номер водительского удостоверения')),
                ('type', models.CharField(choices=[('staff', 'Штатный'), ('hired', 'Наёмный')], default='staff', max_length=10, verbose_name='Тип')),
                ('personal_car', models.CharField(blank=True, max_length=20, verbose_name='Госномер личного авто')),
                ('insurance_num', models.CharField(blank=True, max_length=50, verbose_name='Номер страховки')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за км (₽)')),
                ('weight_coefficient', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Коэффициент веса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='client', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField(verbose_name='Запрос')),
                ('response_text', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'AI запрос',
                'verbose_name_plural': 'AI запросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный адрес',
                'verbose_name_plural': 'Избранные адреса',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Tracking ID')),
                ('origin_address', models.CharField(max_length=255, verbose_name='Адрес отправления')),
                ('origin_lat', models.FloatField(blank=True, null=True, verbose_name='Широта отправления')),
                ('origin_lng', models.FloatField(blank=True, null=True, verbose_name='Долгота отправления')),
                ('dest_address', models.CharField(max_length=255, verbose_name='Адрес назначения')),
                ('dest_lat', models.FloatField(blank=True, null=True, verbose_name='Широта назначения')),
                ('dest_lng', models.FloatField(blank=True, null=True, verbose_name='Долгота назначения')),
                ('cargo_description', models.TextField(blank=True, verbose_name='Описание груза')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём (м³)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (₽)')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Расстояние (км)')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая дата доставки')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата отправки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('in_progress', 'В работе'), ('shipped', 'В пути'), ('delivered', 'Доставлен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='logistics.driver', verbose_name='Водитель')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='logistics.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Госномер')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('capacity_weight', models.IntegerField(verbose_name='Грузоподъёмность (кг)')),
                ('capacity_volume', models.IntegerField(verbose_name='Объём кузова (м³)')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('in_transit', 'В рейсе'), ('maintenance', 'На ремонте')], default='available', max_length=20, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Текущая локация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='logistics.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='logistics.truck', verbose_name='Транспорт'),
        ),
    ]
