# Generated by Django 6.0.1 on 2026-02-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_type',
            field=models.CharField(choices=[('general', 'Обычный груз'), ('fragile', 'Хрупкое'), ('flammable', 'Огнеопасное'), ('perishable', 'Скоропортящееся'), ('hazardous', 'Опасное'), ('oversized', 'Негабаритное'), ('temperature_controlled', 'Температурный режим'), ('other', 'Другое')], default='general', max_length=30, verbose_name='Тип груза'),
        ),
        migrations.AddField(
            model_name='order',
            name='cargo_type_custom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип груза (свой вариант)'),
        ),
    ]
