# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_order_cargo_type_order_cargo_type_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара (что везём)'),
        ),
    ]
